[build]
  command = "npm run build"
  skip_nx_cache = true

[[plugins]]
  package = "@netlify/plugin-nextjs"

[env]
  [env.production]
    SKIP_BLOBS_UPLOAD = "true"
    NEXT_PUBLIC_SUPABASE_URL = "https://dudtddoqmzjgztjipdbz.supabase.co"
    NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1ZHRkZG9xbXpqZ3p0amlwZGJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY1Mjc4MzIsImV4cCI6MjA5MjEwMzgzMn0.r73wIwtreMtqY4z_EgGyxy5thN2hx1dPdLAfBnO_-CI"
    NEXT_PUBLIC_ZAPIER_WEBHOOK_URL = ""
    NEXT_PUBLIC_BASE_URL = ""

[dev]
  command = "npm run dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
