[build]
  command = "npm run build"
  publish = ".next"
  skip_nx_cache = true

[env]
  [env.production]
    SKIP_BLOBS_UPLOAD = "true"
    NEXT_PUBLIC_SUPABASE_URL = ""
    NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
    NEXT_PUBLIC_ZAPIER_WEBHOOK_URL = ""
    NEXT_PUBLIC_BASE_URL = ""

[dev]
  command = "npm run dev"
  port = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
